# Generated by Django 2.2.7 on 2019-11-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('user_age', models.IntegerField()),
                ('user_phone', models.TextField()),
                ('user_address', models.TextField()),
            ],
        ),
    ]
